### ISSUE TITLE
Paperclip::Errors::NotIdentifiedByImageMagickError with Devise

### ISSUE THREAD

**Issue by georgemillo** [rsantamaria/papercrop#10]
I'm trying to set up Papercrop as per the readme but it's not working. I've added the Paperclip columns to my database, the `has_attached_file` and `crop_attached_file` lines to my model, and the `f.cropbox` and `f.crop_preview` lines to my user edit form, but when I try to visit the page I get a `Paperclip::Errors::NotIdentifiedByImageMagickError` - "Cannot find the geometry of a file with a blank name".

This is for an `avatar` attribute on a `User` model which uses Devise... I just copied the same code into the edit page for one of my other models which already has a paperclip attachment, and it works fine. So it seems there's a conflict between Paperclip and Devise, but I don't know enough about either to know where to start debugging.

**Comment by Feuda** [comment]
Me too

**Comment by col-kheiron** [comment]
Same Issue

**Comment by blueteeth** [comment]
same issue...

**Comment by veezus** [comment]
I beat my head against the wall on this error for a while, changing the command_path, removing all image related libraries from machines, re-installing from apt-get (and brew on my MacBook), rebuilding from source in both locations.

It turns out I had an absolute path in my default_url setting. Do not do this.

Correct:
    :default_url => "images/default_photo/:style/default.jpg",

Incorrect:
    :default_url => "/images/default_photo/:style/default.jpg",

Just in case this helps anyone else.

**Comment by Narayanan170** [comment]
This is a paperclip issue because of the incompatible imagemagick version or an improper imagemagick installation. I use a VPS, and I compiled Imagemagick, there was no problem for carrierwave, but paperclip wouldn't work, so I reinstalled Imagemagick from the package manager, and it works fine now...

**Comment by rsantamaria** [comment]
You're right @Narayanan170, this is an imagemagick/paperclip configuration issue.

**Comment by andymilk** [comment]
I'm getting this error as well.

Is there any documentation about how ImageMagick/Paperclip needs to be configured for this to work?

It's working locally on my Mac, but on a Debian production server, I'm getting this error:
ActionView::Template::Error (Paperclip::Errors::NotIdentifiedByImageMagickError):
          
    30:             <%= u.cropbox :placeholder %>

**Comment by Sonblind** [comment]
I'm having the same issue

**Comment by MitchellGeere** [comment]
I have the same issue too. Paperclip works fine, add papercrop and I get this error.

**Comment by IonatanSala** [comment]
Did anyone find a solution to this yet?

**Comment by Sciandra-Leva** [comment]
It may be related to the default_url of the attachment. In my case I had to put it this way:

`    default_url: "public/missing/:style/missing_avatar.jpg",
`
it was missing the `public/` part

**Comment by mkozono** [comment]
This was my issue, after a lot of digging:

**Issue**
Some versions of ImageMagick lock down the HTTPS policy, among others, as a quick security fix for a [major vulnerability](https://imagetragick.com).
1. This causes ImageMagick to fail to use `identify`, for example, directly on files in S3.
2. Which causes Paperclip to [fail to get geometry](https://github.com/thoughtbot/paperclip/issues/2198).
3. Which causes Papercrop to raise `NotIdentifiedByImageMagickError` when rendering `cropbox`.

**Solution**
If you want to use Papercrop and maintain security, then you should **"Upgrade to ImageMagick 7.0.1-1 or newer"**, as recommended in https://robots.thoughtbot.com/paperclip-is-vulnerable-to-the-imagetragick-vulnerability.

**Comment by fwl** [comment]
@mkozono thank you for sharing the results of your investigation. Upgrading to ImageMagick 7.0.x on Heroku didn't solve the issue for us (using Paperclip 5.1.0 and papercrop 0.3.0 with Rails 4.2.8). 

Did you do anything else besides upgrading ImageMagick to solve the issue?

**Comment by mkozono** [comment]
Nope, I believe the upgrade was enough to fix our issue.

**Comment by fwl** [comment]
@mkozono thank you for the quick response.

**Comment by fwl** [comment]
While everything is working fine locally, on Heroku it fails despite using 7.0.5:

```
$ heroku run identify --version
Running identify --version on ⬢ ... up, run.6860 (1X)
Version: ImageMagick 7.0.5-4 Q16 x86_64 2017-04-23 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): bzlib djvu fontconfig freetype gvc jbig jng jpeg lcms lqr lzma openexr png tiff wmf x xml zlib
```

**Comment by fwl** [comment]
For anyone who happens to be reading this because of the same problem, this might help you. Setting the paperclip option `s3_protocol: 'http'` stopped the error. The `identify` command could not access the files on S3 over HTTPS because it's locked down via policy. These two threads below were useful:

http://www.imagemagick.org/discourse-server/viewtopic.php?f=2&t=29657

and

http://www.imagemagick.org/discourse-server/viewtopic.php?t=29592

**Comment by simonfranzen** [comment]
Why is this closed ? I think its not a good idea to solve this issue with just "change https to http". What are the security risk for that ??

I am still having the problem on heroku with paperclip+papercrop+s3:

stack heroku 16
ImageMagick 6.8.9-9 Q16
Rails 4.2.8
paperclip 4.3.6
papercrop 0.3.0

**Comment by aurora-a-k-a-lightning** [comment]
what worked for us was simply just _defining_ the s3_protocol - _it can be_ `'https'`!
```
config.paperclip_defaults = {
      storage: :s3,
      s3_credentials: {
          s3_host_name: "s3-#{region}.amazonaws.com",
          bucket: ENV.fetch('S3_BUCKET_NAME'),
          access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
          secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
          s3_region: region,
      },
      s3_protocol: 'https'
  }
```
