### ISSUE TITLE
Setting minimum crop size

### ISSUE THREAD

**Issue by ezuhaib** [rsantamaria/papercrop#16]
I think having ability to set minimum crop size would be pretty useful, so that images do not have to be up scaled if user selects too small an area.

**Comment by turt13** [comment]
This would be a fantastic feature. Are there any plans to implement minSize and maxSize into the core gem?

**Comment by rsantamaria** [comment]
:+1: 43148602c014289ebfbad0652a9cd0c52662a1bc
