### ISSUE TITLE
How Can I set the aspect ratio to unconstrained ratio?

### ISSUE THREAD

**Issue by Azzurrio** [rsantamaria/papercrop#2]
I just want to make the aspect ratio unconstrained so the user can select whatever s(he) need. The default is 1:1. so How Can I set it to be like this just like this demo http://deepliquid.com/projects/Jcrop/demos.php

**Comment by rsantamaria** [comment]
Done! 5c85a415fc90eb9993e24f2dcd81eb4ef0dcf7c1
