### ISSUE TITLE
how to select new file on cropbox?

### ISSUE THREAD

**Issue by gentle0219** [rsantamaria/papercrop#24]
I'm using now paperclip and papercrop
but this issue happened on f.cropbox of new event page .
url: ...events/new
error message: Paperclip::Errors::NotIdentifiedByImageMagickError

how to solve this issue?

**Comment by rsantamaria** [comment]
Your model must be persisted, and the attachment saved to access the image geometries.

**Comment by Sciandra-Leva** [comment]
> Your model must be persisted, and the attachment saved to access the image geometries.

Can you elaborate a bit over your this? I don't understand.
