### ISSUE TITLE
image_geometry returns the wrong value when called a second time for a different attachment

### ISSUE THREAD

**Issue by ccaratori** [rsantamaria/papercrop#31]
I have a model that has has two attachments and as I wanted to crop both attachments on the same view I came across a bug.

The second time the method image_geometry is called (even for different attachments) returns the same result as the first time because the result is stored in a instance variable and it is not scoped by the attachment name.

If this is really a bug I would be more than happy to submit a pull request to fix it.

**Comment by rsantamaria** [comment]
@ccaratori, thanks for the heads up!
Fixed in 30ab1e09d8e0d763bc6063558f161b416486a67c
