### ISSUE TITLE
Cant run test

### ISSUE THREAD

**Issue by simonini** [rsantamaria/papercrop#44]
Sorry i'm new to testing gem and appraisal.
After installation of Gemfile's dependencies with appraisal i try to do _appraisal rake_ but i get this **LoadError**:

`>> BUNDLE_GEMFILE=/Users/ale/Sites/papercrop/gemfiles/rails_3_2.gemfile bundle exec rake
/Users/ale/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/Users/ale/.rvm/rubies/ruby-2.2.1/bin/ruby -S rspec ./spec/helpers/form_helpers_spec.rb ./spec/integration/papercrop_js_spec.rb ./spec/integration/papercrop_spec.rb ./spec/model_extensions/model_extension_spec.rb ./spec/model_extensions/reg_exp_spec.rb
/Users/ale/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/Users/ale/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in require': cannot load such file -- test/unit/assertions (LoadError)`

What can i do to solve this issue?

Thanks!

**Comment by rsantamaria** [comment]
Hi, thanks for your patience! ruby 2 does not include the test-unit gem by default, and active_support 3.2.13 needs it. This was fixed in b215e14f1f3adb981c293aeb5c7b6124a0fb3ebd
