### ISSUE TITLE
Papercrop is not saving my cropped images

### ISSUE THREAD

**Issue by renegadeandy** [rsantamaria/papercrop#45]
The UI component works flawlessly, and I think I can see traces of the cropping working, but the resulting saved image is the original unchanged. The problem is described in detail here : http://stackoverflow.com/questions/35694968/papercrop-is-not-saving-cropped-image

**Comment by universal** [comment]
As answered there:

This gem does not crop the original image, but only the variations defined in styles :-)

**Comment by renegadeandy** [comment]
So in theory, since I have the styles of medium large and desktop, doing <%= image_tag @event.event_images.first.photo_url(:large) %> should show me the cropped version. It doesnt. It shows the original.
