### ISSUE TITLE
Displaying cropped dimensions

### ISSUE THREAD

**Issue by mikeover** [rsantamaria/papercrop#52]
I'd like to display the dimensions of the cropped image in real time, as the crop gets changed. There are input fields #pic_crop_{n} where n is x, y, w, and h. 

These input fields get their values updated as the crop box changes, however, they do not trigger a change() so there's no way to bind onto it and display their values (at least not nicely).

Please either make this a configuration option or at least trigger change() events when these inputs are updated so they can be used elsewhere.

**Comment by rsantamaria** [comment]
Hi @mikeover, you can use the jcrop_api to set your own callbacks :)

`jcrop_api.setOptions({onChange : showCoords})`

This doesn't break the papercrop's callbacks
